# Netlify config for simple CMS
[build]
  publish = "."

# Enable Netlify Identity for CMS authentication
[build.environment]
  NODE_VERSION = "18"

# Redirect admin to CMS
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
