backend:
  name: github
  repo: Mentle/amanda-website
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "portfolio"
    label: "Portfolio Projects"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Hero Image", name: "heroImage", widget: "image"}
      - label: "Project Images"
        name: "projectImages"
        widget: "list"
        field: {label: "Image", name: "image", widget: "image"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}

  - name: "settings"
    label: "Site Settings"
    files:
      - label: "Site Info"
        name: "site"
        file: "content/settings/site.json"
        fields:
          - {label: "Site Title", name: "siteTitle", widget: "string"}
          - {label: "Portfolio Intro", name: "portfolioIntro", widget: "text"}
          - label: "Contact"
            name: "contact"
            widget: "object"
            fields:
              - {label: "Email", name: "email", widget: "string"}
              - {label: "Phone", name: "phone", widget: "string"}
              - {label: "Location", name: "location", widget: "string"}
